cat:
	cat Makefile


refresh:
	cp /iarpa/opt/usgs-smart-rga/*.yml .
mamba:
	        conda install -c "conda-forge" mamba

gaasspy-env:
	        mamba env create -f environment.yml

smart-env:
	        mamba env create -f environment_ssh.yml

